Loading required package: coda
Linked to JAGS 4.3.0
Loaded modules: basemod,bugs
Loading required package: lattice

Attaching package: 'jagsUI'

The following object is masked from 'package:coda':

    traceplot

The following object is masked from 'package:utils':

    View

[1] "2021-02-02 19:46:01 CET"

Processing function input....... 

Done. 
 
Beginning parallel processing using 3 cores. Console output will be suppressed.
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: RUNTIME ERROR:
Unable to resolve the following parameters:
b[9,1] (line 27, 36)
b[10,1] (line 27, 36)
b[11,1] (line 27, 36)
b[12,1] (line 27, 36)
b[13,1] (line 27, 36)
b[14,1] (line 27, 36)
b[15,1] (line 27, 36)
Either supply values for these nodes with the data
or define them on the left hand side of a relation.

Calls: jags ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
